config/routes.rb
Rails.application.routes.draw do
  root 'players#index'
  
  resources:players
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/player.rb
class Player < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def index
	@player = Player.all
  end
  def new 
  	@player = Player.new
  end
  def create
  	@player = Player.new(player_params)
  	if @player.save
  		redirect_to root_path
  	end
  end
  def show 
  	@player = Player.find_by(id: params[:id])
  end
  def edit
  	@player = Player.find_by(id: params[:id])
  end
  def update
  	@player = Player.find_by(id: params[:id])
  end
  def destroy
  	@player = Player.find_by(id: params[:id])
  end

  private
  	def player_params
  		params.require(:player).permit(:nickname, :rank, :charizma, :wisdom)
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Game</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/players/edit.html.erb
<%= form_for @player, url: player_path(player.id) do |f| %>
  <%= f.text_field :nickname %> <br />
  <%= f.text_field :rank %> <br />
  <%= f.text_field :charizma %> <br />
  <%= f.text_field :wisdom %> <br />
  <%= f.submit "Update" %>
<% end %>

app/views/players/index.html.erb
<%= link_to "New Player", new_player_path %>
<% if @p == [] %>
	<p> No Players </p>
<% else %>
	<% @player.each do |player| %>
		<p>
  			<%= player.nickname %> <br />
  			<%= player.rank %> <br />
  			<%= player.charizma %> <br />
  			<%= player.wisdom %> <br />
  			<%= link_to " delete player ", player_path(player.id) %>
  		</p>
  	<% end %>
 <% end %>

app/views/players/new.html.erb
<%= form_for @player, url: players_path do |f| %>
  <%= f.text_field :nickname %> <br />
  <%= f.text_field :rank %> <br />
  <%= f.text_field :charizma %> <br />
  <%= f.text_field :wisdom %> <br />
  <%= f.submit "Create" %>
<% end %>

app/views/players/show.html.erb
  <%= f.text_field :nickname %> <br />
  <%= f.text_field :rank %> <br />
  <%= f.text_field :charizma  %> <br />
  <%= f.text_field :wisdom  %> <br />
  <%= link_to 'edit', edit_player_path(player.id) %>
  <%= link_to 'delete', player_path(player.id), method: :delete %>